<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Cap'n Proto</string>
    <key>scopeName</key>
    <string>source.capnp</string>
    <key>fileTypes</key>
    <array>
      <string>capnp</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\{\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\}</string>
    <key>uuid</key>
    <string>D65F6EC0-F768-11E3-A1D9-0800273FD7DC</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\#).*$</string>
        <key>name</key>
        <string>comment.line</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(struct|enum|interface|union|import|using|const|annotation|extends|in|of|on|as|with|from|fixed)\b</string>
        <key>name</key>
        <string>keyword.control</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\@\w+</string>
        <key>name</key>
        <string>constant.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(\w+)\s+(@\d+).*-></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>:\w+</string>
        <key>name</key>
        <string>support.type</string>
      </dict>
    </array>
  </dict>
</plist>
